// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {envsetup} from '../models';
import {app} from '../models';
import {producews} from '../models';
import {fivee} from '../models';
import {wanmei} from '../models';
import {demo} from '../models';

export function ApplySelfUpdate():Promise<envsetup.StartupState>;

export function CancelStartupDownload(arg1:string):Promise<envsetup.StartupState>;

export function CheckPlatformClients():Promise<Array<app.PlatformClientStatus>>;

export function ClearDemoDirectory():Promise<app.DemoStorageStats>;

export function ClearOutputsDirectory():Promise<app.OutputsStorageStats>;

export function ConcatEditClips(arg1:app.EditConcatRequest):Promise<string>;

export function EnterMainApp():Promise<void>;

export function ExitApp():Promise<void>;

export function ExportProduceHistoryVideos():Promise<app.ExportProduceHistoryResult>;

export function ExportStartupLogs():Promise<string>;

export function GeneratePluginJSON(arg1:app.GeneratePluginJSONRequest):Promise<app.GeneratePluginJSONResult>;

export function GeneratePluginJSONBatch(arg1:app.GeneratePluginJSONBatchRequest):Promise<app.GeneratePluginJSONBatchResult>;

export function GeneratePluginJSONBatchAndLaunchHLAE(arg1:app.GeneratePluginJSONBatchRequest):Promise<app.GeneratePluginJSONBatchResult>;

export function GetClipActionSettings():Promise<app.ClipActionSettings>;

export function GetClipSettings():Promise<app.ClipSettings>;

export function GetDemoStorageStats():Promise<app.DemoStorageStats>;

export function GetFiveEPlayerName():Promise<string>;

export function GetGameInfoHealth():Promise<app.GameInfoHealth>;

export function GetOutputsStorageStats():Promise<app.OutputsStorageStats>;

export function GetProduceHistorySnapshot():Promise<app.ProduceHistorySnapshot>;

export function GetProduceQueueState():Promise<producews.QueueState>;

export function GetProduceTakeFiles():Promise<app.ProduceTakeFileSnapshot>;

export function GetProduceTakeSnapshot():Promise<producews.TakeStatusSnapshot>;

export function GetProduceWSState():Promise<producews.WSState>;

export function GetStartupState():Promise<envsetup.StartupState>;

export function GetWorkspaceState():Promise<app.WorkspaceState>;

export function ImportFiveEMatch(arg1:string):Promise<Array<string>>;

export function ImportManualDownload(arg1:string):Promise<envsetup.StartupState>;

export function ImportWanmeiMatch(arg1:string):Promise<Array<string>>;

export function ListFiveERecentMatches(arg1:string,arg2:number):Promise<fivee.FiveEMatchListResult>;

export function ListWanmeiRecentMatches(arg1:number):Promise<wanmei.WanmeiMatchListResult>;

export function OpenDemoDirectory():Promise<void>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenManualDownload(arg1:string):Promise<void>;

export function OpenOutputsDirectory():Promise<void>;

export function OpenProducedClipInFolder(arg1:string):Promise<void>;

export function ParseDemoFile(arg1:string):Promise<demo.Metadata>;

export function PickCS2Path():Promise<envsetup.StartupState>;

export function PickDemoFiles():Promise<Array<string>>;

export function PickRecordOutputDir():Promise<string>;

export function PickWorkspaceDir():Promise<string>;

export function PreviewFullRoundPOV(arg1:string,arg2:string):Promise<demo.FullRoundPOVPlan>;

export function ProbeClipDuration(arg1:string):Promise<number>;

export function ReinstallStartupComponent(arg1:string):Promise<envsetup.StartupState>;

export function RepairGameInfo():Promise<app.GameInfoHealth>;

export function RequestClosePlatformClient(arg1:string):Promise<app.PlatformClientCloseResult>;

export function ResetWorkspace():Promise<void>;

export function RetryStartupComponent(arg1:string):Promise<envsetup.StartupState>;

export function RunStartupChecks():Promise<envsetup.StartupState>;

export function SaveClipActionSettings(arg1:app.ClipActionSettings):Promise<app.ClipActionSettings>;

export function SaveClipSettings(arg1:app.ClipSettings):Promise<app.ClipSettings>;

export function SetWorkspaceDir(arg1:string):Promise<void>;

export function ValidateWorkspaceDir(arg1:string):Promise<app.WorkspaceValidateResult>;
