// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplySelfUpdate() {
  return window['go']['app']['App']['ApplySelfUpdate']();
}

export function CheckPlatformClients() {
  return window['go']['app']['App']['CheckPlatformClients']();
}

export function ClearOutputsDirectory() {
  return window['go']['app']['App']['ClearOutputsDirectory']();
}

export function ConcatEditClips(arg1) {
  return window['go']['app']['App']['ConcatEditClips'](arg1);
}

export function EnterMainApp() {
  return window['go']['app']['App']['EnterMainApp']();
}

export function ExportProduceHistoryVideos() {
  return window['go']['app']['App']['ExportProduceHistoryVideos']();
}

export function ExportStartupLogs() {
  return window['go']['app']['App']['ExportStartupLogs']();
}

export function GeneratePluginJSON(arg1) {
  return window['go']['app']['App']['GeneratePluginJSON'](arg1);
}

export function GeneratePluginJSONBatch(arg1) {
  return window['go']['app']['App']['GeneratePluginJSONBatch'](arg1);
}

export function GeneratePluginJSONBatchAndLaunchHLAE(arg1) {
  return window['go']['app']['App']['GeneratePluginJSONBatchAndLaunchHLAE'](arg1);
}

export function GetClipActionSettings() {
  return window['go']['app']['App']['GetClipActionSettings']();
}

export function GetClipSettings() {
  return window['go']['app']['App']['GetClipSettings']();
}

export function GetFiveEPlayerName() {
  return window['go']['app']['App']['GetFiveEPlayerName']();
}

export function GetOutputsStorageStats() {
  return window['go']['app']['App']['GetOutputsStorageStats']();
}

export function GetProduceHistorySnapshot() {
  return window['go']['app']['App']['GetProduceHistorySnapshot']();
}

export function GetProduceQueueState() {
  return window['go']['app']['App']['GetProduceQueueState']();
}

export function GetProduceTakeFiles() {
  return window['go']['app']['App']['GetProduceTakeFiles']();
}

export function GetProduceTakeSnapshot() {
  return window['go']['app']['App']['GetProduceTakeSnapshot']();
}

export function GetProduceWSState() {
  return window['go']['app']['App']['GetProduceWSState']();
}

export function GetStartupState() {
  return window['go']['app']['App']['GetStartupState']();
}

export function ImportFiveEMatch(arg1) {
  return window['go']['app']['App']['ImportFiveEMatch'](arg1);
}

export function ImportManualDownload(arg1) {
  return window['go']['app']['App']['ImportManualDownload'](arg1);
}

export function ImportWanmeiMatch(arg1) {
  return window['go']['app']['App']['ImportWanmeiMatch'](arg1);
}

export function ListFiveERecentMatches(arg1, arg2) {
  return window['go']['app']['App']['ListFiveERecentMatches'](arg1, arg2);
}

export function ListWanmeiRecentMatches(arg1) {
  return window['go']['app']['App']['ListWanmeiRecentMatches'](arg1);
}

export function OpenExternalURL(arg1) {
  return window['go']['app']['App']['OpenExternalURL'](arg1);
}

export function OpenManualDownload(arg1) {
  return window['go']['app']['App']['OpenManualDownload'](arg1);
}

export function OpenOutputsDirectory() {
  return window['go']['app']['App']['OpenOutputsDirectory']();
}

export function OpenProducedClipInFolder(arg1) {
  return window['go']['app']['App']['OpenProducedClipInFolder'](arg1);
}

export function ParseDemoFile(arg1) {
  return window['go']['app']['App']['ParseDemoFile'](arg1);
}

export function PickCS2Path() {
  return window['go']['app']['App']['PickCS2Path']();
}

export function PickDemoFiles() {
  return window['go']['app']['App']['PickDemoFiles']();
}

export function PickRecordOutputDir() {
  return window['go']['app']['App']['PickRecordOutputDir']();
}

export function ProbeClipDuration(arg1) {
  return window['go']['app']['App']['ProbeClipDuration'](arg1);
}

export function ReinstallStartupComponent(arg1) {
  return window['go']['app']['App']['ReinstallStartupComponent'](arg1);
}

export function RequestClosePlatformClient(arg1) {
  return window['go']['app']['App']['RequestClosePlatformClient'](arg1);
}

export function RetryStartupComponent(arg1) {
  return window['go']['app']['App']['RetryStartupComponent'](arg1);
}

export function RunStartupChecks() {
  return window['go']['app']['App']['RunStartupChecks']();
}

export function SaveClipActionSettings(arg1) {
  return window['go']['app']['App']['SaveClipActionSettings'](arg1);
}

export function SaveClipSettings(arg1) {
  return window['go']['app']['App']['SaveClipSettings'](arg1);
}
