// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAndUpdateHLAE(arg1) {
  return window['go']['main']['App']['CheckAndUpdateHLAE'](arg1);
}

export function CheckEnvironment() {
  return window['go']['main']['App']['CheckEnvironment']();
}

export function CheckHLAEEnvironment() {
  return window['go']['main']['App']['CheckHLAEEnvironment']();
}

export function DownloadPerfectWorldDemo(arg1) {
  return window['go']['main']['App']['DownloadPerfectWorldDemo'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetMap2DRenderData(arg1) {
  return window['go']['main']['App']['GetMap2DRenderData'](arg1);
}

export function GetUpdateInfo() {
  return window['go']['main']['App']['GetUpdateInfo']();
}

export function GetUsageStats() {
  return window['go']['main']['App']['GetUsageStats']();
}

export function GetVideoPreviewURL(arg1) {
  return window['go']['main']['App']['GetVideoPreviewURL'](arg1);
}

export function IncrementMakeCount() {
  return window['go']['main']['App']['IncrementMakeCount']();
}

export function IncrementRunCount() {
  return window['go']['main']['App']['IncrementRunCount']();
}

export function OpenVideoExternal(arg1) {
  return window['go']['main']['App']['OpenVideoExternal'](arg1);
}

export function ParseDemo(arg1) {
  return window['go']['main']['App']['ParseDemo'](arg1);
}

export function PickCS2Exe() {
  return window['go']['main']['App']['PickCS2Exe']();
}

export function PickDemo() {
  return window['go']['main']['App']['PickDemo']();
}

export function PickHLAEExe() {
  return window['go']['main']['App']['PickHLAEExe']();
}

export function PickOutputDir() {
  return window['go']['main']['App']['PickOutputDir']();
}

export function PrepareEnvironment(arg1) {
  return window['go']['main']['App']['PrepareEnvironment'](arg1);
}

export function RunWorkflow(arg1) {
  return window['go']['main']['App']['RunWorkflow'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetupFFmpegIni() {
  return window['go']['main']['App']['SetupFFmpegIni']();
}
