// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckAndUpdateHLAE(arg1:boolean):Promise<void>;

export function CheckEnvironment():Promise<void>;

export function CheckHLAEEnvironment():Promise<void>;

export function DownloadPerfectWorldDemo(arg1:string):Promise<string>;

export function GetConfig():Promise<main.Config>;

export function GetVideoPreviewURL(arg1:string):Promise<string>;

export function OpenVideoExternal(arg1:string):Promise<void>;

export function ParseDemo(arg1:string):Promise<main.DemoInfo>;

export function PickCS2Exe():Promise<string>;

export function PickDemo():Promise<string>;

export function PickHLAEExe():Promise<string>;

export function PickOutputDir():Promise<string>;

export function PrepareEnvironment(arg1:boolean):Promise<main.Config>;

export function RunWorkflow(arg1:main.RecordRequest):Promise<main.RecordResult>;

export function SaveConfig(arg1:main.Config):Promise<main.Config>;

export function SetupFFmpegIni():Promise<void>;
